### ISSUE TITLE
training error when saving checkpoint

### ISSUE THREAD

**Issue by wuyi1983** [ijkguo/mx-rcnn#82]
Hi, after finishing the first epoch, I got the following error. How to fix it?
Thanks

INFO:root:Epoch[0] Batch [10020]	Speed: 4.99 samples/sec	Train-RPNAcc=0.990064,	RPNLogLoss=0.034670,	RPNL1Loss=0.447456,	RCNNAcc=0.849728,	RCNNLogLoss=0.468532,	RCNNL1Loss=1.930149,	
INFO:root:Epoch[0] Train-RPNAcc=0.990062
INFO:root:Epoch[0] Train-RPNLogLoss=0.034672
INFO:root:Epoch[0] Train-RPNL1Loss=0.447425
INFO:root:Epoch[0] Train-RCNNAcc=0.849727
INFO:root:Epoch[0] Train-RCNNLogLoss=0.468535
INFO:root:Epoch[0] Train-RCNNL1Loss=1.930103
INFO:root:Epoch[0] Time cost=2069.632
Traceback (most recent call last):
  File "train_end2end.py", line 178, in <module>
    main()
  File "train_end2end.py", line 175, in main
    lr=args.lr, lr_step=args.lr_step)
  File "train_end2end.py", line 137, in train_net
    arg_params=arg_params, aux_params=aux_params, begin_epoch=begin_epoch, num_epoch=end_epoch)
  File "/home/wuyi/anaconda2/lib/python2.7/site-packages/mxnet/module/base_module.py", line 517, in fit
    self.set_params(arg_params, aux_params)
  File "/home/wuyi/anaconda2/lib/python2.7/site-packages/mxnet/module/base_module.py", line 652, in set_params
    allow_extra=allow_extra)
TypeError: init_params() got an unexpected keyword argument 'allow_extra'

**Comment by yaoliUoA** [comment]
I met the same problem, just remove the 'allow_extra' on line  652 in /mxnet/module/base_module.py, and it worked fine for me.
