### ISSUE TITLE
when running "python demo.py --prefix final ............ ", ModuleNotFoundError: No module named 'symbol_vgg'

### ISSUE THREAD

**Issue by hdjsjyl** [ijkguo/mx-rcnn#84]
No module named 'symbol_vgg'.........

**Comment by SaptaGit** [comment]
Same issue

**Comment by taurenexcrement** [comment]
Got past this by just moving symbol_vgg.py into source but then it can't find 'bbox' module. Apparently this has something to do with cython but reinstalling it didn't help.

**Comment by dovatron** [comment]
Have the same issue

**Comment by Ram124** [comment]
@hdjsjyl @SaptaGit @ijkguo @taurenexcrement @dovatron Hello Guys,
Did you guys solve the problem of  

File "/home/ubuntu/MXnet/rcnn/symbol/__init__.py", line 1, in <module>
    from symbol_vgg import *
ModuleNotFoundError: No module named 'symbol_vgg'


I got the above error when i try to run this command
bash script/vgg_voc07.sh 0
´
Any help is really appreciated

**Comment by ijkguo** [comment]
Python 3? I think change to `from .symbol_vgg import *` should work

**Comment by Ram124** [comment]
@ijkguo I got it now.
But now i am getting new error.

Traceback (most recent call last):
  File "test.py", line 5, in <module>
    from rcnn.tools.test_rcnn import test_rcnn
  File "/home/ubuntu/MXnet/rcnn/tools/test_rcnn.py", line 7, in <module>
    from ..symbol import *
  File "/home/ubuntu/MXnet/rcnn/symbol/__init__.py", line 1, in <module>
    from .symbol_vgg import *
  File "/home/ubuntu/MXnet/rcnn/symbol/symbol_vgg.py", line 3, in <module>
    import proposal
ModuleNotFoundError: No module named 'proposal'


what is the issue?

**Comment by ijkguo** [comment]
Check the version. I fixed python 3 compatibility. The current master is different from the error you provide.

**Comment by Ram124** [comment]
Yaa I corrected it.

Now i m getting this error after 1 epoch. How to solve this? Is it related to mxnet version?

Traceback (most recent call last):
File "train_end2end.py", line 178, in 
main()
File "train_end2end.py", line 175, in main
lr=args.lr, lr_step=args.lr_step)
File "train_end2end.py", line 137, in train_net
arg_params=arg_params, aux_params=aux_params, begin_epoch=begin_epoch, num_epoch=end_epoch)
File "/home/ubuntu/anaconda3/envs/mxnet_p27/lib/python2.7/site-packages/mxnet/module/base_module.py", line 517, in fit
self.set_params(arg_params, aux_params)
File "/home/ubuntu/anaconda3/envs/mxnet_p27/lib/python2.7/site-packages/mxnet/module/base_module.py", line 652, in set_params
allow_extra=allow_extra)
TypeError: init_params() got an unexpected keyword argument 'allow_extra'

**Comment by ijkguo** [comment]
Yeah working on new mxnet api right now. Checkout dev branch symnet/module.py. Should be just syntax fix.

**Comment by Ram124** [comment]
Yaa I corrected it.

Now i m getting this error after 1 epoch. How to solve this? Is it related to mxnet version?

Traceback (most recent call last):
File "train_end2end.py", line 178, in 
main()
File "train_end2end.py", line 175, in main
lr=args.lr, lr_step=args.lr_step)
File "train_end2end.py", line 137, in train_net
arg_params=arg_params, aux_params=aux_params, begin_epoch=begin_epoch, num_epoch=end_epoch)
File "/home/ubuntu/anaconda3/envs/mxnet_p27/lib/python2.7/site-packages/mxnet/module/base_module.py", line 517, in fit
self.set_params(arg_params, aux_params)
File "/home/ubuntu/anaconda3/envs/mxnet_p27/lib/python2.7/site-packages/mxnet/module/base_module.py", line 652, in set_params
allow_extra=allow_extra)
TypeError: init_params() got an unexpected keyword argument 'allow_extra'

which mxnet version is required?
I am using mxnet.__version__ : 1.2.0

**Comment by Ram124** [comment]
@ijkguo Thank you for your previous solution

Now I have done training on my own data. 
But when i run a demo on single image to check my model.
 
I am not able to detect 2 classes on same image..
I could only able to detect one object per image.

while training i have given images with single object only.
300 images with pedestrians and 300 images with bicycle. so total 600 images.

Is it because of this?

what would be the problem?

Please help me in this..

**Comment by ijkguo** [comment]
The original issue is related to cython modules, which are removed in the new release.

As for training on your own dataset, you are welcome to open a new issue to detail your modifications.
